/*
 * generated by Xtext 2.17.0
 */
package poc.rules.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import poc.rules.parser.antlr.internal.InternalRuleLanguageParser;
import poc.rules.services.RuleLanguageGrammarAccess;

public class RuleLanguageParser extends AbstractAntlrParser {

	@Inject
	private RuleLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRuleLanguageParser createParser(XtextTokenStream stream) {
		return new InternalRuleLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RuleLanguage";
	}

	public RuleLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RuleLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
