/*
 * generated by Xtext 2.17.0
 */
package poc.rules.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RuleLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("poc/rules/parser/antlr/internal/InternalRuleLanguage.tokens");
	}
}
