/*
 * generated by Xtext 2.17.0
 */
package poc.rules.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRuleLanguageScopeProvider extends DelegatingScopeProvider {
}
