/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import poc.rules.RuleLanguageRuntimeModule;
import poc.rules.RuleLanguageStandaloneSetup;
import poc.rules.ide.RuleLanguageIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RuleLanguageIdeSetup extends RuleLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    RuleLanguageRuntimeModule _ruleLanguageRuntimeModule = new RuleLanguageRuntimeModule();
    RuleLanguageIdeModule _ruleLanguageIdeModule = new RuleLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_ruleLanguageRuntimeModule, _ruleLanguageIdeModule));
  }
}
