/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ide;

import poc.rules.ide.AbstractRuleLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RuleLanguageIdeModule extends AbstractRuleLanguageIdeModule {
}
