/*
 * generated by Xtext 2.17.0
 */
package poc.rules.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import poc.rules.RuleLanguage.ui.internal.RuleLanguageActivator;

public class RuleLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RuleLanguageActivator.getInstance().getInjector("poc.rules.RuleLanguage");
	}

}
