/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link poc.rules.ruleLanguage.Action#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see poc.rules.ruleLanguage.RuleLanguagePackage#getAction()
 * @model
 * @generated
 */
public interface Action extends Element
{
  /**
   * Returns the value of the '<em><b>Param</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' attribute list.
   * @see poc.rules.ruleLanguage.RuleLanguagePackage#getAction_Param()
   * @model unique="false"
   * @generated
   */
  EList<String> getParam();

} // Action
