/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see poc.rules.ruleLanguage.RuleLanguagePackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends ECondition
{
} // Condition
