/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see poc.rules.ruleLanguage.RuleLanguagePackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
