/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see poc.rules.ruleLanguage.RuleLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface RuleLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ruleLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.rules.poc/RuleLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ruleLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RuleLanguagePackage eINSTANCE = poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.RuleLanguageImpl <em>Rule Language</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.RuleLanguageImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getRuleLanguage()
   * @generated
   */
  int RULE_LANGUAGE = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_LANGUAGE__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Rule Language</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_LANGUAGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.ElementImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.RulePackageImpl <em>Rule Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.RulePackageImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getRulePackage()
   * @generated
   */
  int RULE_PACKAGE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_PACKAGE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_PACKAGE__ELEMENTS = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rule Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_PACKAGE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.BookingPhraseImpl <em>Booking Phrase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.BookingPhraseImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getBookingPhrase()
   * @generated
   */
  int BOOKING_PHRASE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING_PHRASE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Booking Phrase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING_PHRASE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.FlightPhraseImpl <em>Flight Phrase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.FlightPhraseImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getFlightPhrase()
   * @generated
   */
  int FLIGHT_PHRASE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_PHRASE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Flight Phrase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_PHRASE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.TripPhraseImpl <em>Trip Phrase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.TripPhraseImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getTripPhrase()
   * @generated
   */
  int TRIP_PHRASE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIP_PHRASE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Trip Phrase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIP_PHRASE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.GuestPhraseImpl <em>Guest Phrase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.GuestPhraseImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getGuestPhrase()
   * @generated
   */
  int GUEST_PHRASE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUEST_PHRASE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Guest Phrase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUEST_PHRASE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.NotificationPhraseImpl <em>Notification Phrase</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.NotificationPhraseImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getNotificationPhrase()
   * @generated
   */
  int NOTIFICATION_PHRASE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION_PHRASE__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Notification Phrase</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION_PHRASE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.NotificationActionImpl <em>Notification Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.NotificationActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getNotificationAction()
   * @generated
   */
  int NOTIFICATION_ACTION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION_ACTION__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Notification Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION_ACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.FlightActionImpl <em>Flight Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.FlightActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getFlightAction()
   * @generated
   */
  int FLIGHT_ACTION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ACTION__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Flight Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_ACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.BookingActionImpl <em>Booking Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.BookingActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getBookingAction()
   * @generated
   */
  int BOOKING_ACTION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING_ACTION__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Booking Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING_ACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.GuestActionImpl <em>Guest Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.GuestActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getGuestAction()
   * @generated
   */
  int GUEST_ACTION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUEST_ACTION__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Guest Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUEST_ACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.TripActionImpl <em>Trip Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.TripActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getTripAction()
   * @generated
   */
  int TRIP_ACTION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIP_ACTION__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Trip Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIP_ACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.RuleImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getRule()
   * @generated
   */
  int RULE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITIONS = 2;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACTIONS = 3;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.EConditionImpl <em>ECondition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.EConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getECondition()
   * @generated
   */
  int ECONDITION = 14;

  /**
   * The number of structural features of the '<em>ECondition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECONDITION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.ConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 15;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = ECONDITION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.SimpleConditionImpl <em>Simple Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.SimpleConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getSimpleCondition()
   * @generated
   */
  int SIMPLE_CONDITION = 16;

  /**
   * The number of structural features of the '<em>Simple Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CONDITION_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.TripConditionImpl <em>Trip Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.TripConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getTripCondition()
   * @generated
   */
  int TRIP_CONDITION = 17;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIP_CONDITION__METHOD = SIMPLE_CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Trip Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIP_CONDITION_FEATURE_COUNT = SIMPLE_CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.GuestConditionImpl <em>Guest Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.GuestConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getGuestCondition()
   * @generated
   */
  int GUEST_CONDITION = 18;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUEST_CONDITION__METHOD = SIMPLE_CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Guest Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUEST_CONDITION_FEATURE_COUNT = SIMPLE_CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.BookingConditionImpl <em>Booking Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.BookingConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getBookingCondition()
   * @generated
   */
  int BOOKING_CONDITION = 19;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING_CONDITION__METHOD = SIMPLE_CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Booking Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOKING_CONDITION_FEATURE_COUNT = SIMPLE_CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.FlightConditionImpl <em>Flight Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.FlightConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getFlightCondition()
   * @generated
   */
  int FLIGHT_CONDITION = 20;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_CONDITION__METHOD = SIMPLE_CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Flight Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_CONDITION_FEATURE_COUNT = SIMPLE_CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.NotificationConditionImpl <em>Notification Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.NotificationConditionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getNotificationCondition()
   * @generated
   */
  int NOTIFICATION_CONDITION = 21;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION_CONDITION__METHOD = SIMPLE_CONDITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Notification Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION_CONDITION_FEATURE_COUNT = SIMPLE_CONDITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.ActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getAction()
   * @generated
   */
  int ACTION = 22;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__PARAM = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.ENotificationActionImpl <em>ENotification Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.ENotificationActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getENotificationAction()
   * @generated
   */
  int ENOTIFICATION_ACTION = 23;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENOTIFICATION_ACTION__PARAM = ACTION__PARAM;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENOTIFICATION_ACTION__METHOD = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>ENotification Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENOTIFICATION_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.EFlightActionImpl <em>EFlight Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.EFlightActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getEFlightAction()
   * @generated
   */
  int EFLIGHT_ACTION = 24;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFLIGHT_ACTION__PARAM = ACTION__PARAM;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFLIGHT_ACTION__METHOD = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>EFlight Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EFLIGHT_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.EBookingActionImpl <em>EBooking Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.EBookingActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getEBookingAction()
   * @generated
   */
  int EBOOKING_ACTION = 25;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBOOKING_ACTION__PARAM = ACTION__PARAM;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBOOKING_ACTION__METHOD = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>EBooking Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EBOOKING_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.EGuestActionImpl <em>EGuest Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.EGuestActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getEGuestAction()
   * @generated
   */
  int EGUEST_ACTION = 26;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EGUEST_ACTION__PARAM = ACTION__PARAM;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EGUEST_ACTION__METHOD = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>EGuest Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EGUEST_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.ETripActionImpl <em>ETrip Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.ETripActionImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getETripAction()
   * @generated
   */
  int ETRIP_ACTION = 27;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETRIP_ACTION__PARAM = ACTION__PARAM;

  /**
   * The feature id for the '<em><b>Method</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETRIP_ACTION__METHOD = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>ETrip Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ETRIP_ACTION_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link poc.rules.ruleLanguage.impl.DecisionTableImpl <em>Decision Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see poc.rules.ruleLanguage.impl.DecisionTableImpl
   * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getDecisionTable()
   * @generated
   */
  int DECISION_TABLE = 28;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_TABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_TABLE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_TABLE__CONDITIONS = 2;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_TABLE__ACTIONS = 3;

  /**
   * The feature id for the '<em><b>Cells</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_TABLE__CELLS = 4;

  /**
   * The number of structural features of the '<em>Decision Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_TABLE_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.RuleLanguage <em>Rule Language</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Language</em>'.
   * @see poc.rules.ruleLanguage.RuleLanguage
   * @generated
   */
  EClass getRuleLanguage();

  /**
   * Returns the meta object for the containment reference list '{@link poc.rules.ruleLanguage.RuleLanguage#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see poc.rules.ruleLanguage.RuleLanguage#getElements()
   * @see #getRuleLanguage()
   * @generated
   */
  EReference getRuleLanguage_Elements();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see poc.rules.ruleLanguage.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.RulePackage <em>Rule Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Package</em>'.
   * @see poc.rules.ruleLanguage.RulePackage
   * @generated
   */
  EClass getRulePackage();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.RulePackage#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.RulePackage#getName()
   * @see #getRulePackage()
   * @generated
   */
  EAttribute getRulePackage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link poc.rules.ruleLanguage.RulePackage#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see poc.rules.ruleLanguage.RulePackage#getElements()
   * @see #getRulePackage()
   * @generated
   */
  EReference getRulePackage_Elements();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.BookingPhrase <em>Booking Phrase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Booking Phrase</em>'.
   * @see poc.rules.ruleLanguage.BookingPhrase
   * @generated
   */
  EClass getBookingPhrase();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.BookingPhrase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.BookingPhrase#getName()
   * @see #getBookingPhrase()
   * @generated
   */
  EAttribute getBookingPhrase_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.FlightPhrase <em>Flight Phrase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flight Phrase</em>'.
   * @see poc.rules.ruleLanguage.FlightPhrase
   * @generated
   */
  EClass getFlightPhrase();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.FlightPhrase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.FlightPhrase#getName()
   * @see #getFlightPhrase()
   * @generated
   */
  EAttribute getFlightPhrase_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.TripPhrase <em>Trip Phrase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trip Phrase</em>'.
   * @see poc.rules.ruleLanguage.TripPhrase
   * @generated
   */
  EClass getTripPhrase();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.TripPhrase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.TripPhrase#getName()
   * @see #getTripPhrase()
   * @generated
   */
  EAttribute getTripPhrase_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.GuestPhrase <em>Guest Phrase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guest Phrase</em>'.
   * @see poc.rules.ruleLanguage.GuestPhrase
   * @generated
   */
  EClass getGuestPhrase();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.GuestPhrase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.GuestPhrase#getName()
   * @see #getGuestPhrase()
   * @generated
   */
  EAttribute getGuestPhrase_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.NotificationPhrase <em>Notification Phrase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Notification Phrase</em>'.
   * @see poc.rules.ruleLanguage.NotificationPhrase
   * @generated
   */
  EClass getNotificationPhrase();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.NotificationPhrase#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.NotificationPhrase#getName()
   * @see #getNotificationPhrase()
   * @generated
   */
  EAttribute getNotificationPhrase_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.NotificationAction <em>Notification Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Notification Action</em>'.
   * @see poc.rules.ruleLanguage.NotificationAction
   * @generated
   */
  EClass getNotificationAction();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.NotificationAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.NotificationAction#getName()
   * @see #getNotificationAction()
   * @generated
   */
  EAttribute getNotificationAction_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.FlightAction <em>Flight Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flight Action</em>'.
   * @see poc.rules.ruleLanguage.FlightAction
   * @generated
   */
  EClass getFlightAction();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.FlightAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.FlightAction#getName()
   * @see #getFlightAction()
   * @generated
   */
  EAttribute getFlightAction_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.BookingAction <em>Booking Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Booking Action</em>'.
   * @see poc.rules.ruleLanguage.BookingAction
   * @generated
   */
  EClass getBookingAction();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.BookingAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.BookingAction#getName()
   * @see #getBookingAction()
   * @generated
   */
  EAttribute getBookingAction_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.GuestAction <em>Guest Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guest Action</em>'.
   * @see poc.rules.ruleLanguage.GuestAction
   * @generated
   */
  EClass getGuestAction();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.GuestAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.GuestAction#getName()
   * @see #getGuestAction()
   * @generated
   */
  EAttribute getGuestAction_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.TripAction <em>Trip Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trip Action</em>'.
   * @see poc.rules.ruleLanguage.TripAction
   * @generated
   */
  EClass getTripAction();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.TripAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.TripAction#getName()
   * @see #getTripAction()
   * @generated
   */
  EAttribute getTripAction_Name();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see poc.rules.ruleLanguage.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.Rule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.Rule#getName()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Name();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.Rule#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see poc.rules.ruleLanguage.Rule#getDescription()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Description();

  /**
   * Returns the meta object for the containment reference list '{@link poc.rules.ruleLanguage.Rule#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see poc.rules.ruleLanguage.Rule#getConditions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Conditions();

  /**
   * Returns the meta object for the containment reference list '{@link poc.rules.ruleLanguage.Rule#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see poc.rules.ruleLanguage.Rule#getActions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Actions();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.ECondition <em>ECondition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ECondition</em>'.
   * @see poc.rules.ruleLanguage.ECondition
   * @generated
   */
  EClass getECondition();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see poc.rules.ruleLanguage.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.SimpleCondition <em>Simple Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Condition</em>'.
   * @see poc.rules.ruleLanguage.SimpleCondition
   * @generated
   */
  EClass getSimpleCondition();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.TripCondition <em>Trip Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trip Condition</em>'.
   * @see poc.rules.ruleLanguage.TripCondition
   * @generated
   */
  EClass getTripCondition();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.TripCondition#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.TripCondition#getMethod()
   * @see #getTripCondition()
   * @generated
   */
  EReference getTripCondition_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.GuestCondition <em>Guest Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Guest Condition</em>'.
   * @see poc.rules.ruleLanguage.GuestCondition
   * @generated
   */
  EClass getGuestCondition();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.GuestCondition#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.GuestCondition#getMethod()
   * @see #getGuestCondition()
   * @generated
   */
  EReference getGuestCondition_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.BookingCondition <em>Booking Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Booking Condition</em>'.
   * @see poc.rules.ruleLanguage.BookingCondition
   * @generated
   */
  EClass getBookingCondition();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.BookingCondition#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.BookingCondition#getMethod()
   * @see #getBookingCondition()
   * @generated
   */
  EReference getBookingCondition_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.FlightCondition <em>Flight Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flight Condition</em>'.
   * @see poc.rules.ruleLanguage.FlightCondition
   * @generated
   */
  EClass getFlightCondition();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.FlightCondition#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.FlightCondition#getMethod()
   * @see #getFlightCondition()
   * @generated
   */
  EReference getFlightCondition_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.NotificationCondition <em>Notification Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Notification Condition</em>'.
   * @see poc.rules.ruleLanguage.NotificationCondition
   * @generated
   */
  EClass getNotificationCondition();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.NotificationCondition#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.NotificationCondition#getMethod()
   * @see #getNotificationCondition()
   * @generated
   */
  EReference getNotificationCondition_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see poc.rules.ruleLanguage.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute list '{@link poc.rules.ruleLanguage.Action#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Param</em>'.
   * @see poc.rules.ruleLanguage.Action#getParam()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Param();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.ENotificationAction <em>ENotification Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ENotification Action</em>'.
   * @see poc.rules.ruleLanguage.ENotificationAction
   * @generated
   */
  EClass getENotificationAction();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.ENotificationAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.ENotificationAction#getMethod()
   * @see #getENotificationAction()
   * @generated
   */
  EReference getENotificationAction_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.EFlightAction <em>EFlight Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EFlight Action</em>'.
   * @see poc.rules.ruleLanguage.EFlightAction
   * @generated
   */
  EClass getEFlightAction();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.EFlightAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.EFlightAction#getMethod()
   * @see #getEFlightAction()
   * @generated
   */
  EReference getEFlightAction_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.EBookingAction <em>EBooking Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EBooking Action</em>'.
   * @see poc.rules.ruleLanguage.EBookingAction
   * @generated
   */
  EClass getEBookingAction();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.EBookingAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.EBookingAction#getMethod()
   * @see #getEBookingAction()
   * @generated
   */
  EReference getEBookingAction_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.EGuestAction <em>EGuest Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EGuest Action</em>'.
   * @see poc.rules.ruleLanguage.EGuestAction
   * @generated
   */
  EClass getEGuestAction();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.EGuestAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.EGuestAction#getMethod()
   * @see #getEGuestAction()
   * @generated
   */
  EReference getEGuestAction_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.ETripAction <em>ETrip Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ETrip Action</em>'.
   * @see poc.rules.ruleLanguage.ETripAction
   * @generated
   */
  EClass getETripAction();

  /**
   * Returns the meta object for the reference list '{@link poc.rules.ruleLanguage.ETripAction#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Method</em>'.
   * @see poc.rules.ruleLanguage.ETripAction#getMethod()
   * @see #getETripAction()
   * @generated
   */
  EReference getETripAction_Method();

  /**
   * Returns the meta object for class '{@link poc.rules.ruleLanguage.DecisionTable <em>Decision Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decision Table</em>'.
   * @see poc.rules.ruleLanguage.DecisionTable
   * @generated
   */
  EClass getDecisionTable();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.DecisionTable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see poc.rules.ruleLanguage.DecisionTable#getName()
   * @see #getDecisionTable()
   * @generated
   */
  EAttribute getDecisionTable_Name();

  /**
   * Returns the meta object for the attribute '{@link poc.rules.ruleLanguage.DecisionTable#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see poc.rules.ruleLanguage.DecisionTable#getDescription()
   * @see #getDecisionTable()
   * @generated
   */
  EAttribute getDecisionTable_Description();

  /**
   * Returns the meta object for the containment reference list '{@link poc.rules.ruleLanguage.DecisionTable#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see poc.rules.ruleLanguage.DecisionTable#getConditions()
   * @see #getDecisionTable()
   * @generated
   */
  EReference getDecisionTable_Conditions();

  /**
   * Returns the meta object for the containment reference list '{@link poc.rules.ruleLanguage.DecisionTable#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see poc.rules.ruleLanguage.DecisionTable#getActions()
   * @see #getDecisionTable()
   * @generated
   */
  EReference getDecisionTable_Actions();

  /**
   * Returns the meta object for the attribute list '{@link poc.rules.ruleLanguage.DecisionTable#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Cells</em>'.
   * @see poc.rules.ruleLanguage.DecisionTable#getCells()
   * @see #getDecisionTable()
   * @generated
   */
  EAttribute getDecisionTable_Cells();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RuleLanguageFactory getRuleLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.RuleLanguageImpl <em>Rule Language</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.RuleLanguageImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getRuleLanguage()
     * @generated
     */
    EClass RULE_LANGUAGE = eINSTANCE.getRuleLanguage();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_LANGUAGE__ELEMENTS = eINSTANCE.getRuleLanguage_Elements();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.ElementImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.RulePackageImpl <em>Rule Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.RulePackageImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getRulePackage()
     * @generated
     */
    EClass RULE_PACKAGE = eINSTANCE.getRulePackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_PACKAGE__NAME = eINSTANCE.getRulePackage_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_PACKAGE__ELEMENTS = eINSTANCE.getRulePackage_Elements();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.BookingPhraseImpl <em>Booking Phrase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.BookingPhraseImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getBookingPhrase()
     * @generated
     */
    EClass BOOKING_PHRASE = eINSTANCE.getBookingPhrase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOKING_PHRASE__NAME = eINSTANCE.getBookingPhrase_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.FlightPhraseImpl <em>Flight Phrase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.FlightPhraseImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getFlightPhrase()
     * @generated
     */
    EClass FLIGHT_PHRASE = eINSTANCE.getFlightPhrase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIGHT_PHRASE__NAME = eINSTANCE.getFlightPhrase_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.TripPhraseImpl <em>Trip Phrase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.TripPhraseImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getTripPhrase()
     * @generated
     */
    EClass TRIP_PHRASE = eINSTANCE.getTripPhrase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIP_PHRASE__NAME = eINSTANCE.getTripPhrase_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.GuestPhraseImpl <em>Guest Phrase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.GuestPhraseImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getGuestPhrase()
     * @generated
     */
    EClass GUEST_PHRASE = eINSTANCE.getGuestPhrase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUEST_PHRASE__NAME = eINSTANCE.getGuestPhrase_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.NotificationPhraseImpl <em>Notification Phrase</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.NotificationPhraseImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getNotificationPhrase()
     * @generated
     */
    EClass NOTIFICATION_PHRASE = eINSTANCE.getNotificationPhrase();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTIFICATION_PHRASE__NAME = eINSTANCE.getNotificationPhrase_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.NotificationActionImpl <em>Notification Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.NotificationActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getNotificationAction()
     * @generated
     */
    EClass NOTIFICATION_ACTION = eINSTANCE.getNotificationAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTIFICATION_ACTION__NAME = eINSTANCE.getNotificationAction_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.FlightActionImpl <em>Flight Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.FlightActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getFlightAction()
     * @generated
     */
    EClass FLIGHT_ACTION = eINSTANCE.getFlightAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIGHT_ACTION__NAME = eINSTANCE.getFlightAction_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.BookingActionImpl <em>Booking Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.BookingActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getBookingAction()
     * @generated
     */
    EClass BOOKING_ACTION = eINSTANCE.getBookingAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOKING_ACTION__NAME = eINSTANCE.getBookingAction_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.GuestActionImpl <em>Guest Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.GuestActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getGuestAction()
     * @generated
     */
    EClass GUEST_ACTION = eINSTANCE.getGuestAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GUEST_ACTION__NAME = eINSTANCE.getGuestAction_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.TripActionImpl <em>Trip Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.TripActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getTripAction()
     * @generated
     */
    EClass TRIP_ACTION = eINSTANCE.getTripAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIP_ACTION__NAME = eINSTANCE.getTripAction_Name();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.RuleImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRule_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__DESCRIPTION = eINSTANCE.getRule_Description();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITIONS = eINSTANCE.getRule_Conditions();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ACTIONS = eINSTANCE.getRule_Actions();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.EConditionImpl <em>ECondition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.EConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getECondition()
     * @generated
     */
    EClass ECONDITION = eINSTANCE.getECondition();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.ConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.SimpleConditionImpl <em>Simple Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.SimpleConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getSimpleCondition()
     * @generated
     */
    EClass SIMPLE_CONDITION = eINSTANCE.getSimpleCondition();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.TripConditionImpl <em>Trip Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.TripConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getTripCondition()
     * @generated
     */
    EClass TRIP_CONDITION = eINSTANCE.getTripCondition();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIP_CONDITION__METHOD = eINSTANCE.getTripCondition_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.GuestConditionImpl <em>Guest Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.GuestConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getGuestCondition()
     * @generated
     */
    EClass GUEST_CONDITION = eINSTANCE.getGuestCondition();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GUEST_CONDITION__METHOD = eINSTANCE.getGuestCondition_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.BookingConditionImpl <em>Booking Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.BookingConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getBookingCondition()
     * @generated
     */
    EClass BOOKING_CONDITION = eINSTANCE.getBookingCondition();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOOKING_CONDITION__METHOD = eINSTANCE.getBookingCondition_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.FlightConditionImpl <em>Flight Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.FlightConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getFlightCondition()
     * @generated
     */
    EClass FLIGHT_CONDITION = eINSTANCE.getFlightCondition();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT_CONDITION__METHOD = eINSTANCE.getFlightCondition_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.NotificationConditionImpl <em>Notification Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.NotificationConditionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getNotificationCondition()
     * @generated
     */
    EClass NOTIFICATION_CONDITION = eINSTANCE.getNotificationCondition();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOTIFICATION_CONDITION__METHOD = eINSTANCE.getNotificationCondition_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.ActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__PARAM = eINSTANCE.getAction_Param();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.ENotificationActionImpl <em>ENotification Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.ENotificationActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getENotificationAction()
     * @generated
     */
    EClass ENOTIFICATION_ACTION = eINSTANCE.getENotificationAction();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENOTIFICATION_ACTION__METHOD = eINSTANCE.getENotificationAction_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.EFlightActionImpl <em>EFlight Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.EFlightActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getEFlightAction()
     * @generated
     */
    EClass EFLIGHT_ACTION = eINSTANCE.getEFlightAction();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EFLIGHT_ACTION__METHOD = eINSTANCE.getEFlightAction_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.EBookingActionImpl <em>EBooking Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.EBookingActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getEBookingAction()
     * @generated
     */
    EClass EBOOKING_ACTION = eINSTANCE.getEBookingAction();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EBOOKING_ACTION__METHOD = eINSTANCE.getEBookingAction_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.EGuestActionImpl <em>EGuest Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.EGuestActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getEGuestAction()
     * @generated
     */
    EClass EGUEST_ACTION = eINSTANCE.getEGuestAction();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EGUEST_ACTION__METHOD = eINSTANCE.getEGuestAction_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.ETripActionImpl <em>ETrip Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.ETripActionImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getETripAction()
     * @generated
     */
    EClass ETRIP_ACTION = eINSTANCE.getETripAction();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ETRIP_ACTION__METHOD = eINSTANCE.getETripAction_Method();

    /**
     * The meta object literal for the '{@link poc.rules.ruleLanguage.impl.DecisionTableImpl <em>Decision Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see poc.rules.ruleLanguage.impl.DecisionTableImpl
     * @see poc.rules.ruleLanguage.impl.RuleLanguagePackageImpl#getDecisionTable()
     * @generated
     */
    EClass DECISION_TABLE = eINSTANCE.getDecisionTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_TABLE__NAME = eINSTANCE.getDecisionTable_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_TABLE__DESCRIPTION = eINSTANCE.getDecisionTable_Description();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECISION_TABLE__CONDITIONS = eINSTANCE.getDecisionTable_Conditions();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECISION_TABLE__ACTIONS = eINSTANCE.getDecisionTable_Actions();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_TABLE__CELLS = eINSTANCE.getDecisionTable_Cells();

  }

} //RuleLanguagePackage
