/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Package</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link poc.rules.ruleLanguage.RulePackage#getName <em>Name</em>}</li>
 *   <li>{@link poc.rules.ruleLanguage.RulePackage#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see poc.rules.ruleLanguage.RuleLanguagePackage#getRulePackage()
 * @model
 * @generated
 */
public interface RulePackage extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see poc.rules.ruleLanguage.RuleLanguagePackage#getRulePackage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link poc.rules.ruleLanguage.RulePackage#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see poc.rules.ruleLanguage.RuleLanguagePackage#getRulePackage_Elements()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getElements();

} // RulePackage
