/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see poc.rules.ruleLanguage.RuleLanguagePackage
 * @generated
 */
public interface RuleLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RuleLanguageFactory eINSTANCE = poc.rules.ruleLanguage.impl.RuleLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Rule Language</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Language</em>'.
   * @generated
   */
  RuleLanguage createRuleLanguage();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Rule Package</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Package</em>'.
   * @generated
   */
  RulePackage createRulePackage();

  /**
   * Returns a new object of class '<em>Booking Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Booking Phrase</em>'.
   * @generated
   */
  BookingPhrase createBookingPhrase();

  /**
   * Returns a new object of class '<em>Flight Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flight Phrase</em>'.
   * @generated
   */
  FlightPhrase createFlightPhrase();

  /**
   * Returns a new object of class '<em>Trip Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trip Phrase</em>'.
   * @generated
   */
  TripPhrase createTripPhrase();

  /**
   * Returns a new object of class '<em>Guest Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guest Phrase</em>'.
   * @generated
   */
  GuestPhrase createGuestPhrase();

  /**
   * Returns a new object of class '<em>Notification Phrase</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Notification Phrase</em>'.
   * @generated
   */
  NotificationPhrase createNotificationPhrase();

  /**
   * Returns a new object of class '<em>Notification Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Notification Action</em>'.
   * @generated
   */
  NotificationAction createNotificationAction();

  /**
   * Returns a new object of class '<em>Flight Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flight Action</em>'.
   * @generated
   */
  FlightAction createFlightAction();

  /**
   * Returns a new object of class '<em>Booking Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Booking Action</em>'.
   * @generated
   */
  BookingAction createBookingAction();

  /**
   * Returns a new object of class '<em>Guest Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guest Action</em>'.
   * @generated
   */
  GuestAction createGuestAction();

  /**
   * Returns a new object of class '<em>Trip Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trip Action</em>'.
   * @generated
   */
  TripAction createTripAction();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>ECondition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ECondition</em>'.
   * @generated
   */
  ECondition createECondition();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Simple Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Condition</em>'.
   * @generated
   */
  SimpleCondition createSimpleCondition();

  /**
   * Returns a new object of class '<em>Trip Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trip Condition</em>'.
   * @generated
   */
  TripCondition createTripCondition();

  /**
   * Returns a new object of class '<em>Guest Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Guest Condition</em>'.
   * @generated
   */
  GuestCondition createGuestCondition();

  /**
   * Returns a new object of class '<em>Booking Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Booking Condition</em>'.
   * @generated
   */
  BookingCondition createBookingCondition();

  /**
   * Returns a new object of class '<em>Flight Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flight Condition</em>'.
   * @generated
   */
  FlightCondition createFlightCondition();

  /**
   * Returns a new object of class '<em>Notification Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Notification Condition</em>'.
   * @generated
   */
  NotificationCondition createNotificationCondition();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>ENotification Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ENotification Action</em>'.
   * @generated
   */
  ENotificationAction createENotificationAction();

  /**
   * Returns a new object of class '<em>EFlight Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EFlight Action</em>'.
   * @generated
   */
  EFlightAction createEFlightAction();

  /**
   * Returns a new object of class '<em>EBooking Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EBooking Action</em>'.
   * @generated
   */
  EBookingAction createEBookingAction();

  /**
   * Returns a new object of class '<em>EGuest Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EGuest Action</em>'.
   * @generated
   */
  EGuestAction createEGuestAction();

  /**
   * Returns a new object of class '<em>ETrip Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ETrip Action</em>'.
   * @generated
   */
  ETripAction createETripAction();

  /**
   * Returns a new object of class '<em>Decision Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decision Table</em>'.
   * @generated
   */
  DecisionTable createDecisionTable();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  RuleLanguagePackage getRuleLanguagePackage();

} //RuleLanguageFactory
