/**
 * generated by Xtext 2.17.0
 */
package poc.rules;

import poc.rules.RuleLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RuleLanguageStandaloneSetup extends RuleLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new RuleLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
