/**
 * generated by Xtext 2.17.0
 */
package poc.rules;

import poc.rules.AbstractRuleLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RuleLanguageRuntimeModule extends AbstractRuleLanguageRuntimeModule {
}
