/*
 * generated by Xtext 2.17.0
 */
package poc.rules.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRuleLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(poc.rules.ruleLanguage.RuleLanguagePackage.eINSTANCE);
		return result;
	}
}
