/*
 * generated by Xtext 2.17.0
 */
package poc.rules.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import poc.rules.RuleLanguage.ui.internal.RuleLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RuleLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RuleLanguageActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RuleLanguageActivator activator = RuleLanguageActivator.getInstance();
		return activator != null ? activator.getInjector(RuleLanguageActivator.POC_RULES_RULELANGUAGE) : null;
	}

}
