/*
 * generated by Xtext 2.17.0
 */
package poc.rules


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RuleLanguageRuntimeModule extends AbstractRuleLanguageRuntimeModule {
}
