/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import poc.rules.ruleLanguage.Condition;
import poc.rules.ruleLanguage.RuleLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConditionImpl extends EConditionImpl implements Condition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RuleLanguagePackage.Literals.CONDITION;
  }

} //ConditionImpl
