/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import poc.rules.ruleLanguage.Action;
import poc.rules.ruleLanguage.DecisionTable;
import poc.rules.ruleLanguage.RuleLanguagePackage;
import poc.rules.ruleLanguage.SimpleCondition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Decision Table</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link poc.rules.ruleLanguage.impl.DecisionTableImpl#getName <em>Name</em>}</li>
 *   <li>{@link poc.rules.ruleLanguage.impl.DecisionTableImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link poc.rules.ruleLanguage.impl.DecisionTableImpl#getConditions <em>Conditions</em>}</li>
 *   <li>{@link poc.rules.ruleLanguage.impl.DecisionTableImpl#getActions <em>Actions</em>}</li>
 *   <li>{@link poc.rules.ruleLanguage.impl.DecisionTableImpl#getCells <em>Cells</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DecisionTableImpl extends MinimalEObjectImpl.Container implements DecisionTable
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getConditions() <em>Conditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditions()
   * @generated
   * @ordered
   */
  protected EList<SimpleCondition> conditions;

  /**
   * The cached value of the '{@link #getActions() <em>Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActions()
   * @generated
   * @ordered
   */
  protected EList<Action> actions;

  /**
   * The cached value of the '{@link #getCells() <em>Cells</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCells()
   * @generated
   * @ordered
   */
  protected EList<String> cells;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DecisionTableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RuleLanguagePackage.Literals.DECISION_TABLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RuleLanguagePackage.DECISION_TABLE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RuleLanguagePackage.DECISION_TABLE__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SimpleCondition> getConditions()
  {
    if (conditions == null)
    {
      conditions = new EObjectContainmentEList<SimpleCondition>(SimpleCondition.class, this, RuleLanguagePackage.DECISION_TABLE__CONDITIONS);
    }
    return conditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Action> getActions()
  {
    if (actions == null)
    {
      actions = new EObjectContainmentEList<Action>(Action.class, this, RuleLanguagePackage.DECISION_TABLE__ACTIONS);
    }
    return actions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getCells()
  {
    if (cells == null)
    {
      cells = new EDataTypeEList<String>(String.class, this, RuleLanguagePackage.DECISION_TABLE__CELLS);
    }
    return cells;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RuleLanguagePackage.DECISION_TABLE__CONDITIONS:
        return ((InternalEList<?>)getConditions()).basicRemove(otherEnd, msgs);
      case RuleLanguagePackage.DECISION_TABLE__ACTIONS:
        return ((InternalEList<?>)getActions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RuleLanguagePackage.DECISION_TABLE__NAME:
        return getName();
      case RuleLanguagePackage.DECISION_TABLE__DESCRIPTION:
        return getDescription();
      case RuleLanguagePackage.DECISION_TABLE__CONDITIONS:
        return getConditions();
      case RuleLanguagePackage.DECISION_TABLE__ACTIONS:
        return getActions();
      case RuleLanguagePackage.DECISION_TABLE__CELLS:
        return getCells();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RuleLanguagePackage.DECISION_TABLE__NAME:
        setName((String)newValue);
        return;
      case RuleLanguagePackage.DECISION_TABLE__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case RuleLanguagePackage.DECISION_TABLE__CONDITIONS:
        getConditions().clear();
        getConditions().addAll((Collection<? extends SimpleCondition>)newValue);
        return;
      case RuleLanguagePackage.DECISION_TABLE__ACTIONS:
        getActions().clear();
        getActions().addAll((Collection<? extends Action>)newValue);
        return;
      case RuleLanguagePackage.DECISION_TABLE__CELLS:
        getCells().clear();
        getCells().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RuleLanguagePackage.DECISION_TABLE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RuleLanguagePackage.DECISION_TABLE__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case RuleLanguagePackage.DECISION_TABLE__CONDITIONS:
        getConditions().clear();
        return;
      case RuleLanguagePackage.DECISION_TABLE__ACTIONS:
        getActions().clear();
        return;
      case RuleLanguagePackage.DECISION_TABLE__CELLS:
        getCells().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RuleLanguagePackage.DECISION_TABLE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RuleLanguagePackage.DECISION_TABLE__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case RuleLanguagePackage.DECISION_TABLE__CONDITIONS:
        return conditions != null && !conditions.isEmpty();
      case RuleLanguagePackage.DECISION_TABLE__ACTIONS:
        return actions != null && !actions.isEmpty();
      case RuleLanguagePackage.DECISION_TABLE__CELLS:
        return cells != null && !cells.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", description: ");
    result.append(description);
    result.append(", cells: ");
    result.append(cells);
    result.append(')');
    return result.toString();
  }

} //DecisionTableImpl
