/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ruleLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import poc.rules.ruleLanguage.RuleLanguagePackage;
import poc.rules.ruleLanguage.SimpleCondition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleConditionImpl extends ConditionImpl implements SimpleCondition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleConditionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RuleLanguagePackage.Literals.SIMPLE_CONDITION;
  }

} //SimpleConditionImpl
