/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ui.contentassist;

import poc.rules.ui.contentassist.AbstractRuleLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RuleLanguageProposalProvider extends AbstractRuleLanguageProposalProvider {
}
