/*
 * generated by Xtext 2.17.0
 */
package poc.rules.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import poc.rules.ide.contentassist.antlr.internal.InternalRuleLanguageParser;
import poc.rules.services.RuleLanguageGrammarAccess;

public class RuleLanguageParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RuleLanguageGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RuleLanguageGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getRulePackageAccess().getElementsAlternatives_3_0(), "rule__RulePackage__ElementsAlternatives_3_0");
			builder.put(grammarAccess.getEConditionAccess().getAlternatives_0(), "rule__ECondition__Alternatives_0");
			builder.put(grammarAccess.getSimpleConditionAccess().getAlternatives(), "rule__SimpleCondition__Alternatives");
			builder.put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
			builder.put(grammarAccess.getTripConditionAccess().getAlternatives_2_1(), "rule__TripCondition__Alternatives_2_1");
			builder.put(grammarAccess.getTripConditionAccess().getAlternatives_3_0(), "rule__TripCondition__Alternatives_3_0");
			builder.put(grammarAccess.getTripConditionAccess().getAlternatives_3_2_1(), "rule__TripCondition__Alternatives_3_2_1");
			builder.put(grammarAccess.getGuestConditionAccess().getAlternatives_2_1(), "rule__GuestCondition__Alternatives_2_1");
			builder.put(grammarAccess.getGuestConditionAccess().getAlternatives_3_0(), "rule__GuestCondition__Alternatives_3_0");
			builder.put(grammarAccess.getGuestConditionAccess().getAlternatives_3_2_1(), "rule__GuestCondition__Alternatives_3_2_1");
			builder.put(grammarAccess.getBookingConditionAccess().getAlternatives_2_1(), "rule__BookingCondition__Alternatives_2_1");
			builder.put(grammarAccess.getBookingConditionAccess().getAlternatives_3_0(), "rule__BookingCondition__Alternatives_3_0");
			builder.put(grammarAccess.getBookingConditionAccess().getAlternatives_3_2_1(), "rule__BookingCondition__Alternatives_3_2_1");
			builder.put(grammarAccess.getFlightConditionAccess().getAlternatives_2_1(), "rule__FlightCondition__Alternatives_2_1");
			builder.put(grammarAccess.getFlightConditionAccess().getAlternatives_3_0(), "rule__FlightCondition__Alternatives_3_0");
			builder.put(grammarAccess.getFlightConditionAccess().getAlternatives_3_2_1(), "rule__FlightCondition__Alternatives_3_2_1");
			builder.put(grammarAccess.getNotificationConditionAccess().getAlternatives_2_1(), "rule__NotificationCondition__Alternatives_2_1");
			builder.put(grammarAccess.getNotificationConditionAccess().getAlternatives_3_0(), "rule__NotificationCondition__Alternatives_3_0");
			builder.put(grammarAccess.getNotificationConditionAccess().getAlternatives_3_2_1(), "rule__NotificationCondition__Alternatives_3_2_1");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getENotificationActionAccess().getParamAlternatives_2_0(), "rule__ENotificationAction__ParamAlternatives_2_0");
			builder.put(grammarAccess.getENotificationActionAccess().getParamAlternatives_3_2_0(), "rule__ENotificationAction__ParamAlternatives_3_2_0");
			builder.put(grammarAccess.getEFlightActionAccess().getParamAlternatives_2_0(), "rule__EFlightAction__ParamAlternatives_2_0");
			builder.put(grammarAccess.getEFlightActionAccess().getParamAlternatives_3_2_0(), "rule__EFlightAction__ParamAlternatives_3_2_0");
			builder.put(grammarAccess.getEBookingActionAccess().getParamAlternatives_2_0(), "rule__EBookingAction__ParamAlternatives_2_0");
			builder.put(grammarAccess.getEBookingActionAccess().getParamAlternatives_3_2_0(), "rule__EBookingAction__ParamAlternatives_3_2_0");
			builder.put(grammarAccess.getEGuestActionAccess().getParamAlternatives_2_0(), "rule__EGuestAction__ParamAlternatives_2_0");
			builder.put(grammarAccess.getEGuestActionAccess().getParamAlternatives_3_2_0(), "rule__EGuestAction__ParamAlternatives_3_2_0");
			builder.put(grammarAccess.getETripActionAccess().getParamAlternatives_2_0(), "rule__ETripAction__ParamAlternatives_2_0");
			builder.put(grammarAccess.getETripActionAccess().getParamAlternatives_3_2_0(), "rule__ETripAction__ParamAlternatives_3_2_0");
			builder.put(grammarAccess.getVALUEAccess().getAlternatives(), "rule__VALUE__Alternatives");
			builder.put(grammarAccess.getRulePackageAccess().getGroup(), "rule__RulePackage__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getBookingPhraseAccess().getGroup(), "rule__BookingPhrase__Group__0");
			builder.put(grammarAccess.getFlightPhraseAccess().getGroup(), "rule__FlightPhrase__Group__0");
			builder.put(grammarAccess.getTripPhraseAccess().getGroup(), "rule__TripPhrase__Group__0");
			builder.put(grammarAccess.getGuestPhraseAccess().getGroup(), "rule__GuestPhrase__Group__0");
			builder.put(grammarAccess.getNotificationPhraseAccess().getGroup(), "rule__NotificationPhrase__Group__0");
			builder.put(grammarAccess.getNotificationActionAccess().getGroup(), "rule__NotificationAction__Group__0");
			builder.put(grammarAccess.getFlightActionAccess().getGroup(), "rule__FlightAction__Group__0");
			builder.put(grammarAccess.getBookingActionAccess().getGroup(), "rule__BookingAction__Group__0");
			builder.put(grammarAccess.getGuestActionAccess().getGroup(), "rule__GuestAction__Group__0");
			builder.put(grammarAccess.getTripActionAccess().getGroup(), "rule__TripAction__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup_2(), "rule__Rule__Group_2__0");
			builder.put(grammarAccess.getRuleAccess().getGroup_3(), "rule__Rule__Group_3__0");
			builder.put(grammarAccess.getRuleAccess().getGroup_6(), "rule__Rule__Group_6__0");
			builder.put(grammarAccess.getEConditionAccess().getGroup(), "rule__ECondition__Group__0");
			builder.put(grammarAccess.getTripConditionAccess().getGroup(), "rule__TripCondition__Group__0");
			builder.put(grammarAccess.getTripConditionAccess().getGroup_2(), "rule__TripCondition__Group_2__0");
			builder.put(grammarAccess.getTripConditionAccess().getGroup_3(), "rule__TripCondition__Group_3__0");
			builder.put(grammarAccess.getTripConditionAccess().getGroup_3_2(), "rule__TripCondition__Group_3_2__0");
			builder.put(grammarAccess.getGuestConditionAccess().getGroup(), "rule__GuestCondition__Group__0");
			builder.put(grammarAccess.getGuestConditionAccess().getGroup_2(), "rule__GuestCondition__Group_2__0");
			builder.put(grammarAccess.getGuestConditionAccess().getGroup_3(), "rule__GuestCondition__Group_3__0");
			builder.put(grammarAccess.getGuestConditionAccess().getGroup_3_2(), "rule__GuestCondition__Group_3_2__0");
			builder.put(grammarAccess.getBookingConditionAccess().getGroup(), "rule__BookingCondition__Group__0");
			builder.put(grammarAccess.getBookingConditionAccess().getGroup_2(), "rule__BookingCondition__Group_2__0");
			builder.put(grammarAccess.getBookingConditionAccess().getGroup_3(), "rule__BookingCondition__Group_3__0");
			builder.put(grammarAccess.getBookingConditionAccess().getGroup_3_2(), "rule__BookingCondition__Group_3_2__0");
			builder.put(grammarAccess.getFlightConditionAccess().getGroup(), "rule__FlightCondition__Group__0");
			builder.put(grammarAccess.getFlightConditionAccess().getGroup_2(), "rule__FlightCondition__Group_2__0");
			builder.put(grammarAccess.getFlightConditionAccess().getGroup_3(), "rule__FlightCondition__Group_3__0");
			builder.put(grammarAccess.getFlightConditionAccess().getGroup_3_2(), "rule__FlightCondition__Group_3_2__0");
			builder.put(grammarAccess.getNotificationConditionAccess().getGroup(), "rule__NotificationCondition__Group__0");
			builder.put(grammarAccess.getNotificationConditionAccess().getGroup_2(), "rule__NotificationCondition__Group_2__0");
			builder.put(grammarAccess.getNotificationConditionAccess().getGroup_3(), "rule__NotificationCondition__Group_3__0");
			builder.put(grammarAccess.getNotificationConditionAccess().getGroup_3_2(), "rule__NotificationCondition__Group_3_2__0");
			builder.put(grammarAccess.getENotificationActionAccess().getGroup(), "rule__ENotificationAction__Group__0");
			builder.put(grammarAccess.getENotificationActionAccess().getGroup_3(), "rule__ENotificationAction__Group_3__0");
			builder.put(grammarAccess.getEFlightActionAccess().getGroup(), "rule__EFlightAction__Group__0");
			builder.put(grammarAccess.getEFlightActionAccess().getGroup_3(), "rule__EFlightAction__Group_3__0");
			builder.put(grammarAccess.getEBookingActionAccess().getGroup(), "rule__EBookingAction__Group__0");
			builder.put(grammarAccess.getEBookingActionAccess().getGroup_3(), "rule__EBookingAction__Group_3__0");
			builder.put(grammarAccess.getEGuestActionAccess().getGroup(), "rule__EGuestAction__Group__0");
			builder.put(grammarAccess.getEGuestActionAccess().getGroup_3(), "rule__EGuestAction__Group_3__0");
			builder.put(grammarAccess.getETripActionAccess().getGroup(), "rule__ETripAction__Group__0");
			builder.put(grammarAccess.getETripActionAccess().getGroup_3(), "rule__ETripAction__Group_3__0");
			builder.put(grammarAccess.getVALUESAccess().getGroup(), "rule__VALUES__Group__0");
			builder.put(grammarAccess.getVALUESAccess().getGroup_2(), "rule__VALUES__Group_2__0");
			builder.put(grammarAccess.getDecisionTableAccess().getGroup(), "rule__DecisionTable__Group__0");
			builder.put(grammarAccess.getDecisionTableAccess().getGroup_2(), "rule__DecisionTable__Group_2__0");
			builder.put(grammarAccess.getDecisionTableAccess().getGroup_5(), "rule__DecisionTable__Group_5__0");
			builder.put(grammarAccess.getDecisionTableAccess().getGroup_9(), "rule__DecisionTable__Group_9__0");
			builder.put(grammarAccess.getDecisionTableAccess().getGroup_10(), "rule__DecisionTable__Group_10__0");
			builder.put(grammarAccess.getDecisionTableAccess().getGroup_10_3(), "rule__DecisionTable__Group_10_3__0");
			builder.put(grammarAccess.getRuleLanguageAccess().getElementsAssignment(), "rule__RuleLanguage__ElementsAssignment");
			builder.put(grammarAccess.getRulePackageAccess().getNameAssignment_1(), "rule__RulePackage__NameAssignment_1");
			builder.put(grammarAccess.getRulePackageAccess().getElementsAssignment_3(), "rule__RulePackage__ElementsAssignment_3");
			builder.put(grammarAccess.getBookingPhraseAccess().getNameAssignment_1(), "rule__BookingPhrase__NameAssignment_1");
			builder.put(grammarAccess.getFlightPhraseAccess().getNameAssignment_1(), "rule__FlightPhrase__NameAssignment_1");
			builder.put(grammarAccess.getTripPhraseAccess().getNameAssignment_1(), "rule__TripPhrase__NameAssignment_1");
			builder.put(grammarAccess.getGuestPhraseAccess().getNameAssignment_1(), "rule__GuestPhrase__NameAssignment_1");
			builder.put(grammarAccess.getNotificationPhraseAccess().getNameAssignment_1(), "rule__NotificationPhrase__NameAssignment_1");
			builder.put(grammarAccess.getNotificationActionAccess().getNameAssignment_1(), "rule__NotificationAction__NameAssignment_1");
			builder.put(grammarAccess.getFlightActionAccess().getNameAssignment_1(), "rule__FlightAction__NameAssignment_1");
			builder.put(grammarAccess.getBookingActionAccess().getNameAssignment_1(), "rule__BookingAction__NameAssignment_1");
			builder.put(grammarAccess.getGuestActionAccess().getNameAssignment_1(), "rule__GuestAction__NameAssignment_1");
			builder.put(grammarAccess.getTripActionAccess().getNameAssignment_1(), "rule__TripAction__NameAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getDescriptionAssignment_2_1(), "rule__Rule__DescriptionAssignment_2_1");
			builder.put(grammarAccess.getRuleAccess().getConditionsAssignment_3_1(), "rule__Rule__ConditionsAssignment_3_1");
			builder.put(grammarAccess.getRuleAccess().getActionsAssignment_5(), "rule__Rule__ActionsAssignment_5");
			builder.put(grammarAccess.getRuleAccess().getActionsAssignment_6_1(), "rule__Rule__ActionsAssignment_6_1");
			builder.put(grammarAccess.getTripConditionAccess().getMethodAssignment_1(), "rule__TripCondition__MethodAssignment_1");
			builder.put(grammarAccess.getTripConditionAccess().getMethodAssignment_3_1(), "rule__TripCondition__MethodAssignment_3_1");
			builder.put(grammarAccess.getGuestConditionAccess().getMethodAssignment_1(), "rule__GuestCondition__MethodAssignment_1");
			builder.put(grammarAccess.getGuestConditionAccess().getMethodAssignment_3_1(), "rule__GuestCondition__MethodAssignment_3_1");
			builder.put(grammarAccess.getBookingConditionAccess().getMethodAssignment_1(), "rule__BookingCondition__MethodAssignment_1");
			builder.put(grammarAccess.getBookingConditionAccess().getMethodAssignment_3_1(), "rule__BookingCondition__MethodAssignment_3_1");
			builder.put(grammarAccess.getFlightConditionAccess().getMethodAssignment_1(), "rule__FlightCondition__MethodAssignment_1");
			builder.put(grammarAccess.getFlightConditionAccess().getMethodAssignment_3_1(), "rule__FlightCondition__MethodAssignment_3_1");
			builder.put(grammarAccess.getNotificationConditionAccess().getMethodAssignment_1(), "rule__NotificationCondition__MethodAssignment_1");
			builder.put(grammarAccess.getNotificationConditionAccess().getMethodAssignment_3_1(), "rule__NotificationCondition__MethodAssignment_3_1");
			builder.put(grammarAccess.getENotificationActionAccess().getMethodAssignment_1(), "rule__ENotificationAction__MethodAssignment_1");
			builder.put(grammarAccess.getENotificationActionAccess().getParamAssignment_2(), "rule__ENotificationAction__ParamAssignment_2");
			builder.put(grammarAccess.getENotificationActionAccess().getMethodAssignment_3_1(), "rule__ENotificationAction__MethodAssignment_3_1");
			builder.put(grammarAccess.getENotificationActionAccess().getParamAssignment_3_2(), "rule__ENotificationAction__ParamAssignment_3_2");
			builder.put(grammarAccess.getEFlightActionAccess().getMethodAssignment_1(), "rule__EFlightAction__MethodAssignment_1");
			builder.put(grammarAccess.getEFlightActionAccess().getParamAssignment_2(), "rule__EFlightAction__ParamAssignment_2");
			builder.put(grammarAccess.getEFlightActionAccess().getMethodAssignment_3_1(), "rule__EFlightAction__MethodAssignment_3_1");
			builder.put(grammarAccess.getEFlightActionAccess().getParamAssignment_3_2(), "rule__EFlightAction__ParamAssignment_3_2");
			builder.put(grammarAccess.getEBookingActionAccess().getMethodAssignment_1(), "rule__EBookingAction__MethodAssignment_1");
			builder.put(grammarAccess.getEBookingActionAccess().getParamAssignment_2(), "rule__EBookingAction__ParamAssignment_2");
			builder.put(grammarAccess.getEBookingActionAccess().getMethodAssignment_3_1(), "rule__EBookingAction__MethodAssignment_3_1");
			builder.put(grammarAccess.getEBookingActionAccess().getParamAssignment_3_2(), "rule__EBookingAction__ParamAssignment_3_2");
			builder.put(grammarAccess.getEGuestActionAccess().getMethodAssignment_1(), "rule__EGuestAction__MethodAssignment_1");
			builder.put(grammarAccess.getEGuestActionAccess().getParamAssignment_2(), "rule__EGuestAction__ParamAssignment_2");
			builder.put(grammarAccess.getEGuestActionAccess().getMethodAssignment_3_1(), "rule__EGuestAction__MethodAssignment_3_1");
			builder.put(grammarAccess.getEGuestActionAccess().getParamAssignment_3_2(), "rule__EGuestAction__ParamAssignment_3_2");
			builder.put(grammarAccess.getETripActionAccess().getMethodAssignment_1(), "rule__ETripAction__MethodAssignment_1");
			builder.put(grammarAccess.getETripActionAccess().getParamAssignment_2(), "rule__ETripAction__ParamAssignment_2");
			builder.put(grammarAccess.getETripActionAccess().getMethodAssignment_3_1(), "rule__ETripAction__MethodAssignment_3_1");
			builder.put(grammarAccess.getETripActionAccess().getParamAssignment_3_2(), "rule__ETripAction__ParamAssignment_3_2");
			builder.put(grammarAccess.getDecisionTableAccess().getNameAssignment_1(), "rule__DecisionTable__NameAssignment_1");
			builder.put(grammarAccess.getDecisionTableAccess().getDescriptionAssignment_2_1(), "rule__DecisionTable__DescriptionAssignment_2_1");
			builder.put(grammarAccess.getDecisionTableAccess().getConditionsAssignment_4(), "rule__DecisionTable__ConditionsAssignment_4");
			builder.put(grammarAccess.getDecisionTableAccess().getConditionsAssignment_5_1(), "rule__DecisionTable__ConditionsAssignment_5_1");
			builder.put(grammarAccess.getDecisionTableAccess().getActionsAssignment_7(), "rule__DecisionTable__ActionsAssignment_7");
			builder.put(grammarAccess.getDecisionTableAccess().getActionsAssignment_9_0(), "rule__DecisionTable__ActionsAssignment_9_0");
			builder.put(grammarAccess.getDecisionTableAccess().getCellsAssignment_10_1(), "rule__DecisionTable__CellsAssignment_10_1");
			builder.put(grammarAccess.getDecisionTableAccess().getCellsAssignment_10_3_0(), "rule__DecisionTable__CellsAssignment_10_3_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RuleLanguageGrammarAccess grammarAccess;

	@Override
	protected InternalRuleLanguageParser createParser() {
		InternalRuleLanguageParser result = new InternalRuleLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RuleLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RuleLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
