/*
 * generated by Xtext 2.17.0
 */
package poc.rules.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import poc.rules.RuleLanguageRuntimeModule
import poc.rules.RuleLanguageStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RuleLanguageIdeSetup extends RuleLanguageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RuleLanguageRuntimeModule, new RuleLanguageIdeModule))
	}
	
}
