/**
 * generated by Xtext 2.17.0
 */
package poc.rules.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import poc.rules.ui.AbstractRuleLanguageUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RuleLanguageUiModule extends AbstractRuleLanguageUiModule {
  public RuleLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
